# Gitlab CI configuration for deploying your app to AWS S3 bucket.
# Next you will need to setup Amazon CodeDeploy to listen to changes in your bucket and deploy the zip file.
#
# You will have to setup 4 variables in your Gitlab setup for the AWS SDK to pick you your AMI credentials
# AWS_ACCESS_KEY_ID, AWS_BUCKET, AWS_REGION, AWS_SECRET_ACCESS_KEY

stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  artifacts:
    untracked: true
  script:
    - yarn install
    - yarn build

## Deployment - Develop
deploy_dev:
  image: napp/docker-aws-cli
  stage: deploy
  when: manual
  dependencies:
    - build
  script:
    - cd ./dist
    - aws s3 sync . s3://$AWS_BUCKET/ --delete
  environment:
    name: develop
    url: https://dev-m.bruno.fyi
  only:
    - develop
  variables:
    AWS_BUCKET: 'dev-m.bruno.fyi'

## Deployment - Production
deploy_prod:
  image: napp/docker-aws-cli
  stage: deploy
  when: manual
  dependencies:
    - build
  script:
    - cd ./dist
    - aws s3 sync . s3://$AWS_BUCKET/personal-showcase --delete
  environment:
    name: production
    url: https://m.bruno.fyi
  only:
    - master
  variables:
    AWS_BUCKET: 'mbruno-static-files'
